import { z } from "zod";

const password = z.string().min(8).max(72).regex(/[A-Z]/, "Password must contain an uppercase letter").regex(/[a-z]/, "Password must contain a lowercase letter").regex(/[0-9]/, "Password must contain a number").refine((value) => !/(password|12345678|qwerty|letmein)/i.test(value), "Password is too common");
const email = z.string().trim().toLowerCase().email().max(254);
export const registerSchema = z.object({ name: z.string().trim().min(2).max(100), email, password }).strict();
export const loginSchema = z.object({ email, password: z.string().min(1).max(72) }).strict();
export const forgotPasswordSchema = z.object({ email }).strict();
export const resetPasswordSchema = z.object({ token: z.string().min(32).max(256), password }).strict();
export const verifyEmailSchema = z.object({ token: z.string().min(32).max(256) }).strict();
export const changePasswordSchema = z.object({ currentPassword: z.string().min(1).max(72), newPassword: password }).strict();
export const organizerUpgradeSchema = z.object({ organizationName: z.string().trim().min(2).max(160), slug: z.string().trim().min(2).max(100).regex(/^[a-z0-9-]+$/), bio: z.string().trim().max(2000).optional(), website: z.string().url().optional() }).strict();
export type RegisterInput = z.infer<typeof registerSchema>;
export type LoginInput = z.infer<typeof loginSchema>;
export const profileUpdateSchema = z.object({ name: z.string().trim().min(2).max(100).optional(), phone: z.string().trim().max(30).nullable().optional(), profileImage: z.string().url().nullable().optional() }).strict();
export const categorySchema = z.object({ name: z.string().trim().min(2).max(80), slug: z.string().trim().regex(/^[a-z0-9-]+$/).max(100), sortOrder: z.number().int().min(0).max(10000).default(0) }).strict();
export const eventSchema = z.object({ categoryId: z.string().uuid(), venueId: z.string().uuid().nullable().optional(), title: z.string().trim().min(2).max(200), slug: z.string().trim().regex(/^[a-z0-9-]+$/), description: z.string().max(10000).optional(), city: z.string().max(100).optional(), startsAt: z.coerce.date(), endsAt: z.coerce.date(), capacity: z.number().int().positive().nullable().optional() }).strict().refine((v) => v.endsAt > v.startsAt, { message: "endsAt must be after startsAt" });
const ticketTypeFields = { name: z.string().trim().min(2).max(100), description: z.string().max(1000).optional(), price: z.coerce.number().nonnegative().finite(), quantity: z.number().int().positive(), maxPerUser: z.number().int().positive().nullable().optional(), saleStart: z.coerce.date(), saleEnd: z.coerce.date() };
export const ticketTypeSchema = z.object(ticketTypeFields).strict().refine((v) => v.saleEnd > v.saleStart, { message: "saleEnd must be after saleStart" });
export const ticketTypeUpdateSchema = z.object(ticketTypeFields).partial().strict().refine((v) => !v.saleStart || !v.saleEnd || v.saleEnd > v.saleStart, { message: "saleEnd must be after saleStart" });
export const eventQuerySchema = z.object({search:z.string().max(200).optional(),category:z.string().max(100).optional(),city:z.string().max(100).optional(),status:z.enum(["PUBLISHED"]).optional(),dateFrom:z.coerce.date().optional(),dateTo:z.coerce.date().optional(),priceMin:z.coerce.number().nonnegative().optional(),priceMax:z.coerce.number().nonnegative().optional(),featured:z.enum(["true","false"]).optional(),sort:z.enum(["date","created","title","price"]).optional(),order:z.enum(["asc","desc"]).optional(),page:z.coerce.number().int().min(1).default(1),limit:z.coerce.number().int().min(1).max(100).default(20)}).strict();
export const registrationSchema = z.object({ eventId: z.string().uuid(), items: z.array(z.object({ ticketTypeId: z.string().uuid(), quantity: z.number().int().positive().max(20) }).strict()).min(1).max(20) }).strict();
export const reviewSchema = z.object({ rating: z.number().int().min(1).max(5), comment: z.string().max(2000).optional() }).strict();
