import { Router } from "express";
import crypto from "node:crypto";
import QRCode from "qrcode";
import { prisma } from "../../lib/prisma.js";
import { requireAuth } from "../../middleware/auth.js";
import { requireRoles } from "../../middleware/roles.js";
import { ticketTypeUpdateSchema } from "@festify/validation";
const db=prisma as any;const r=Router();
const safe=(t:any)=>({id:t.id,ticketNumber:t.ticket_number??t.ticket_code,status:t.status,createdAt:t.created_at,event:t.title?{id:t.event_id,title:t.title,startsAt:t.starts_at}:undefined});
async function ticketFor(req:any){const rows=await db.$queryRaw`SELECT t.*,e.id AS event_id,e.title,e.starts_at,op.user_id AS organizer_user_id FROM "ticket" t JOIN "registration" reg ON reg.id=t.registration_id JOIN "event" e ON e.id=reg.event_id JOIN "organizer_profile" op ON op.id=e.organizer_id WHERE t.id=${String(req.params.id)} LIMIT 1`;return rows[0]}
function authorized(t:any,req:any){return req.user.role==='ADMIN'||t.user_id===req.user.id||t.organizer_user_id===req.user.id}
r.get("/tickets/:id",requireAuth,async(req:any,res)=>{try{const t=await ticketFor(req);if(!t)return res.status(404).json({success:false,error:{code:"NOT_FOUND",message:"Ticket not found"}});if(!authorized(t,req))return res.status(403).json({success:false,error:{code:"FORBIDDEN",message:"Not authorized"}});return res.json({success:true,data:safe(t)})}catch(e){return res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Unable to load ticket"}})}});
r.get("/tickets/:id/qr",requireAuth,async(req:any,res)=>{try{const t=await ticketFor(req);if(!t||!authorized(t,req))return res.status(t?403:404).json({success:false,error:{code:t?"FORBIDDEN":"NOT_FOUND",message:t?"Not authorized":"Ticket not found"}});const png=await QRCode.toBuffer(String(t.qr_token),{type:"png",errorCorrectionLevel:"M"});res.type("png").send(png)}catch(e){return res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Unable to generate QR"}})}});
async function lookup(raw:string){const rows=await db.$queryRaw`SELECT t.*,reg.status AS registration_status,e.id AS event_id,e.title,e.starts_at,op.user_id AS organizer_user_id FROM "ticket" t JOIN "registration" reg ON reg.id=t.registration_id JOIN "event" e ON e.id=reg.event_id JOIN "organizer_profile" op ON op.id=e.organizer_id WHERE t.qr_token=${raw} OR t.ticket_code=${raw} OR t.ticket_number=${raw} LIMIT 1`;return rows[0]}
r.post("/tickets/validate",requireAuth,requireRoles("ORGANIZER","ADMIN"),async(req:any,res)=>{try{const t=await lookup(String(req.body?.token??""));if(!t)return res.status(404).json({success:false,error:{code:"NOT_FOUND",message:"Ticket not found"}});if(req.user.role!=="ADMIN"&&t.organizer_user_id!==req.user.id)return res.status(403).json({success:false,error:{code:"FORBIDDEN",message:"Not authorized"}});const checked=await db.$queryRaw`SELECT id FROM "check_in" WHERE ticket_id=${t.id}`;if(t.status!=="ACTIVE"||t.registration_status!=="CONFIRMED")return res.status(409).json({success:false,error:{code:"INVALID_TICKET",message:"Ticket is not valid"}});return res.json({success:true,data:{valid:!checked[0],ticket:safe(t),alreadyCheckedIn:Boolean(checked[0])}})}catch(e){return res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Unable to validate ticket"}})}});
async function checkOne(req:any,raw:string){const t=await lookup(raw);if(!t)throw Object.assign(new Error("Ticket not found"),{code:"NOT_FOUND",status:404});if(req.user.role!=="ADMIN"&&t.organizer_user_id!==req.user.id)throw Object.assign(new Error("Not authorized"),{code:"FORBIDDEN",status:403});return db.$transaction(async(tx:any)=>{const existing=await tx.$queryRaw`SELECT id FROM "check_in" WHERE ticket_id=${t.id} FOR UPDATE`;if(existing[0])throw Object.assign(new Error("Ticket already checked in"),{code:"CONFLICT",status:409});if(t.status!=="ACTIVE"||t.registration_status!=="CONFIRMED")throw Object.assign(new Error("Invalid ticket"),{code:"INVALID_TICKET",status:409});await tx.$executeRaw`INSERT INTO "check_in" (id,ticket_id,operator_id,checked_in_at,status) VALUES (${crypto.randomUUID()},${t.id},${req.user.id},CURRENT_TIMESTAMP,'VALID')`;await tx.$executeRaw`UPDATE "ticket" SET status='USED',updated_at=CURRENT_TIMESTAMP WHERE id=${t.id}`;return safe(t)})}
r.post("/check-ins",requireAuth,requireRoles("ORGANIZER","ADMIN"),async(req:any,res)=>{try{return res.status(201).json({success:true,data:await checkOne(req,String(req.body?.token??req.body?.ticketId??""))})}catch(e:any){return res.status(e.status??500).json({success:false,error:{code:e.code??"INTERNAL_ERROR",message:e.message}})}});
r.post("/check-ins/bulk",requireAuth,requireRoles("ORGANIZER","ADMIN"),async(req:any,res)=>{const tokens=Array.isArray(req.body?.tokens)?req.body.tokens:[];const results=[];for(const x of [...new Set(tokens)])try{results.push({token:x,success:true,ticket:await checkOne(req,String(x))})}catch(e:any){results.push({token:x,success:false,error:e.code??"ERROR"})}return res.json({success:true,data:results})});
r.patch("/ticket-types/:id",requireAuth,requireRoles("ORGANIZER","ADMIN"),async(req:any,res)=>{try{const parsed=ticketTypeUpdateSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({success:false,error:{code:"VALIDATION_ERROR",message:"Invalid ticket type"}});const body=parsed.data;const t=(await db.$queryRaw`SELECT tt.*,o.user_id FROM "ticket_type" tt JOIN "event" e ON e.id=tt.event_id JOIN "organizer_profile" o ON o.id=e.organizer_id WHERE tt.id=${String(req.params.id)}`)[0];if(!t)return res.status(404).json({success:false,error:{code:"NOT_FOUND",message:"Ticket type not found"}});if(req.user.role!=="ADMIN"&&t.user_id!==req.user.id)return res.status(403).json({success:false,error:{code:"FORBIDDEN",message:"Not authorized"}});if(t.sold_quantity>Number(body.quantity??t.quantity))return res.status(409).json({success:false,error:{code:"CONFLICT",message:"Quantity cannot be below sold inventory"}});const x=await db.$queryRaw`UPDATE "ticket_type" SET name=${String(body.name??t.name)},description=${body.description??t.description},price=${Number(body.price??t.price)},quantity=${Number(body.quantity??t.quantity)},max_per_user=${body.maxPerUser??t.max_per_user},sale_start=${body.saleStart??t.sale_start},sale_end=${body.saleEnd??t.sale_end},updated_at=CURRENT_TIMESTAMP WHERE id=${t.id} RETURNING id,name,description,price,quantity,sold_quantity,max_per_user,sale_start,sale_end`;return res.json({success:true,data:x[0]})}catch(e){return res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Unable to update ticket type"}})}});
r.delete("/ticket-types/:id",requireAuth,requireRoles("ORGANIZER","ADMIN"),async(req:any,res)=>{try{const t=(await db.$queryRaw`SELECT tt.*,o.user_id FROM "ticket_type" tt JOIN "event" e ON e.id=tt.event_id JOIN "organizer_profile" o ON o.id=e.organizer_id WHERE tt.id=${String(req.params.id)}`)[0];if(!t)return res.status(404).json({success:false,error:{code:"NOT_FOUND",message:"Ticket type not found"}});if(req.user.role!=="ADMIN"&&t.user_id!==req.user.id)return res.status(403).json({success:false,error:{code:"FORBIDDEN",message:"Not authorized"}});await db.$executeRaw`UPDATE "ticket_type" SET active=false,status='INACTIVE',updated_at=CURRENT_TIMESTAMP WHERE id=${t.id}`;return res.json({success:true,data:null})}catch(e){return res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Unable to delete ticket type"}})}});
r.get("/events/:id/check-ins",requireAuth,requireRoles("ORGANIZER","ADMIN"),async(req:any,res)=>{try{const ok=req.user.role==='ADMIN'||(await db.$queryRaw`SELECT 1 FROM "event" e JOIN "organizer_profile" o ON o.id=e.organizer_id WHERE e.id=${String(req.params.id)} AND o.user_id=${req.user.id}`)[0];if(!ok)return res.status(403).json({success:false,error:{code:"FORBIDDEN",message:"Not authorized"}});return res.json({success:true,data:await db.$queryRaw`SELECT c.id,c.checked_in_at,c.status,t.ticket_number FROM "check_in" c JOIN "ticket" t ON t.id=c.ticket_id JOIN "registration" r ON r.id=t.registration_id WHERE r.event_id=${String(req.params.id)} ORDER BY c.checked_in_at DESC`})}catch(e){return res.status(500).json({success:false,error:{code:"INTERNAL_ERROR",message:"Unable to load check-ins"}})}});
export default r;
