import crypto from "node:crypto";
import type { Request, Response } from "express";
import { categorySchema,eventSchema,eventQuerySchema,ticketTypeSchema,profileUpdateSchema,reviewSchema } from "@festify/validation";
import type { AuthenticatedRequest } from "../../middleware/auth.js";
import { prisma } from "../../lib/prisma.js";
import * as s from "./core.service.js";
const db=prisma as any;
const fail=(res:Response,e:any)=>res.status(e.status??500).json({success:false,error:{code:e.code??"INTERNAL_ERROR",message:e.message??"Internal server error"}});
const parse=(res:Response,schema:any,body:any)=>{const p=schema.safeParse(body);if(!p.success){res.status(400).json({success:false,error:{code:"VALIDATION_ERROR",message:"Invalid request",details:p.error.flatten().fieldErrors}});return null}return p.data};
export async function categories(_req:Request,res:Response){return res.json({success:true,data:await s.listCategories()});}
export async function categoryCreate(req:AuthenticatedRequest,res:Response){const d=parse(res,categorySchema,req.body);if(!d)return;try{return res.status(201).json({success:true,data:await s.createCategory(d)})}catch(e){return fail(res,e)}}
export async function categoryUpdate(req:AuthenticatedRequest,res:Response){const d=parse(res,categorySchema,req.body);if(!d)return;try{return res.json({success:true,data:await s.updateCategory(String(req.params.id),d)})}catch(e){return fail(res,e)}}
export async function categoryDelete(req:AuthenticatedRequest,res:Response){try{return res.json({success:true,data:await s.deleteCategory(String(req.params.id))})}catch(e){return fail(res,e)}}
export async function events(req:Request,res:Response){const parsed=eventQuerySchema.safeParse(req.query);if(!parsed.success)return res.status(400).json({success:false,error:{code:"VALIDATION_ERROR",message:"Invalid event filters"}});try{return res.json({success:true,...await s.listEvents(parsed.data)})}catch(e){return fail(res,e)}}
export async function myEvents(req:AuthenticatedRequest,res:Response){try{return res.json({success:true,data:await s.listOwnedEvents(req.user!.id)})}catch(e){return fail(res,e)}}
export async function managedEvent(req:AuthenticatedRequest,res:Response){try{return res.json({success:true,data:await s.ownedEvent(req.user!.id,String(req.params.id))})}catch(e){return fail(res,e)}}
export async function event(req:Request,res:Response){try{return res.json({success:true,data:await s.eventBySlug(String(req.params.slug))})}catch(e){return fail(res,e)}}
export async function eventCreate(req:AuthenticatedRequest,res:Response){const d=parse(res,eventSchema,req.body);if(!d)return;try{return res.status(201).json({success:true,data:await s.createEvent(req.user!.id,d)})}catch(e){return fail(res,e)}}
export async function eventPublish(req:AuthenticatedRequest,res:Response){try{return res.json({success:true,data:await s.publishEvent(req.user!.id,String(req.params.id),req.user!.role==='ADMIN')})}catch(e){return fail(res,e)}}
export async function eventCancel(req:AuthenticatedRequest,res:Response){try{return res.json({success:true,data:await s.cancelEvent(req.user!.id,String(req.params.id),req.user!.role==='ADMIN')})}catch(e){return fail(res,e)}}
export async function eventUpdate(req:AuthenticatedRequest,res:Response){const d=parse(res,eventSchema,req.body);if(!d)return;try{const e=await s.eventOwned(req.user!.id,String(req.params.id));const rows=await db.$queryRaw`UPDATE "event" SET "title"=${d.title},"description"=${d.description??null},"city"=${d.city??null},"starts_at"=${d.startsAt},"ends_at"=${d.endsAt},"capacity"=${d.capacity??null},"updated_at"=CURRENT_TIMESTAMP WHERE "id"=${e.id} RETURNING *`;return res.json({success:true,data:rows[0]})}catch(e){return fail(res,e)}}
export async function eventDelete(req:AuthenticatedRequest,res:Response){try{await s.cancelEvent(req.user!.id,String(req.params.id),req.user!.role==='ADMIN');return res.json({success:true,data:null,message:"Event cancelled"})}catch(e){return fail(res,e)}}
export async function ticketTypes(req:Request,res:Response){try{const rows=await db.$queryRaw`SELECT * FROM "ticket_type" WHERE "event_id"=${String(req.params.eventId)} ORDER BY "price"`;return res.json({success:true,data:rows})}catch(e){return fail(res,e)}}
export async function ticketTypeCreate(req:AuthenticatedRequest,res:Response){const d=parse(res,ticketTypeSchema,req.body);if(!d)return;try{await s.eventOwned(req.user!.id,String(req.params.eventId));const id=crypto.randomUUID();await db.$executeRaw`INSERT INTO "ticket_type" ("id","event_id","name","description","price","quantity","sale_start","sale_end","max_per_user","status","active","created_at","updated_at") VALUES (${id},${String(req.params.eventId)},${d.name},${d.description??null},${d.price},${d.quantity},${d.saleStart},${d.saleEnd},${d.maxPerUser??null},'ACTIVE',true,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;return res.status(201).json({success:true,data:{id,...d}})}catch(e){return fail(res,e)}}
export async function profile(req:AuthenticatedRequest,res:Response){try{const u=await prisma.user.findUnique({where:{id:req.user!.id}});return res.json({success:true,data:{id:u.id,name:u.name,email:u.email,phone:u.phone,profileImage:u.profileImage,status:u.status,role:req.user!.role}})}catch(e){return fail(res,e)}}
export async function profileDelete(req:AuthenticatedRequest,res:Response){try{await prisma.user.update({where:{id:req.user!.id},data:{status:"INACTIVE",email:`deleted-${req.user!.id}@invalid.local`,name:"Deleted user",passwordHash:"!deactivated"}});return res.json({success:true,data:null,message:"Account deactivated"})}catch(e){return fail(res,e)}}
export async function profileUpdate(req:AuthenticatedRequest,res:Response){const d=parse(res,profileUpdateSchema,req.body);if(!d)return;try{const u=await prisma.user.update({where:{id:req.user!.id},data:d});return res.json({success:true,data:{id:u.id,name:u.name,email:u.email,phone:u.phone,profileImage:u.profileImage,status:u.status}})}catch(e){return fail(res,e)}}
export async function favorites(req:AuthenticatedRequest,res:Response){try{const rows=await db.$queryRaw`SELECT e.* FROM "event_favorite" f JOIN "event" e ON e.id=f.event_id WHERE f.user_id=${req.user!.id} ORDER BY f.created_at DESC`;return res.json({success:true,data:rows})}catch(e){return fail(res,e)}}
export async function favoriteAdd(req:AuthenticatedRequest,res:Response){try{await db.$executeRaw`INSERT INTO "event_favorite" ("user_id","event_id","created_at") VALUES (${req.user!.id},${String(req.params.eventId)},CURRENT_TIMESTAMP) ON CONFLICT ("user_id","event_id") DO NOTHING`;return res.status(201).json({success:true,data:null})}catch(e){return fail(res,e)}}
export async function favoriteRemove(req:AuthenticatedRequest,res:Response){try{await db.$executeRaw`DELETE FROM "event_favorite" WHERE "user_id"=${req.user!.id} AND "event_id"=${String(req.params.eventId)}`;return res.json({success:true,data:null})}catch(e){return fail(res,e)}}
export async function notifications(req:AuthenticatedRequest,res:Response){try{return res.json({success:true,data:await db.$queryRaw`SELECT "id","title","message","read_at","created_at" FROM "notification" WHERE "user_id"=${req.user!.id} ORDER BY "created_at" DESC`})}catch(e){return fail(res,e)}}
export async function notificationRead(req:AuthenticatedRequest,res:Response){try{const rows=await db.$queryRaw`UPDATE "notification" SET "read_at"=CURRENT_TIMESTAMP WHERE "id"=${String(req.params.id)} AND "user_id"=${req.user!.id} RETURNING "id","read_at"`;if(!rows[0])return res.status(404).json({success:false,error:{code:"NOT_FOUND",message:"Notification not found"}});return res.json({success:true,data:rows[0]})}catch(e){return fail(res,e)}}
export async function reviews(req:Request,res:Response){try{return res.json({success:true,data:await db.$queryRaw`SELECT r.id,r.rating,r.comment,r.created_at,u.name AS user_name FROM "event_review" r JOIN "user" u ON u.id=r.user_id WHERE r.event_id=${String(req.params.id)} ORDER BY r.created_at DESC`})}catch(e){return fail(res,e)}}
export async function reviewCreate(req:AuthenticatedRequest,res:Response){const d=parse(res,reviewSchema,req.body);if(!d)return;try{const exists=await db.$queryRaw`SELECT 1 FROM "registration" WHERE "user_id"=${req.user!.id} AND "event_id"=${String(req.params.id)} AND "status"='CONFIRMED'`;if(!exists[0])throw new s.CoreError("FORBIDDEN","You must have a confirmed registration",403);const id=crypto.randomUUID();await db.$executeRaw`INSERT INTO "event_review" ("id","user_id","event_id","rating","comment","created_at","updated_at") VALUES (${id},${req.user!.id},${String(req.params.id)},${d.rating},${d.comment??null},CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;return res.status(201).json({success:true,data:{id,...d}})}catch(e){return fail(res,e)}}
