import crypto from "node:crypto";
import { prisma } from "../../lib/prisma.js";
const db = prisma as any;
export class CoreError extends Error { constructor(public code: string, message: string, public status=400){super(message);} }
const page = (value: unknown, fallback=1) => Math.max(1, Number(value)||fallback);
const limit = (value: unknown, fallback=20) => Math.min(100, Math.max(1, Number(value)||fallback));
export async function listCategories(){return db.$queryRaw`SELECT "id","name","slug","sort_order","status","created_at" FROM "category" WHERE "status"='ACTIVE' ORDER BY "sort_order","name"`;}
export async function createCategory(data:any){const id=crypto.randomUUID(); try {await db.$executeRaw`INSERT INTO "category" ("id","name","slug","sort_order","status","created_at","updated_at") VALUES (${id},${data.name},${data.slug},${data.sortOrder},'ACTIVE',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;} catch(e){throw new CoreError("CONFLICT","Category name or slug already exists",409)} return {id,...data,status:"ACTIVE"};}
export async function updateCategory(id:string,data:any){const rows=await db.$queryRaw`UPDATE "category" SET "name"=${data.name},"slug"=${data.slug},"sort_order"=${data.sortOrder},"updated_at"=CURRENT_TIMESTAMP WHERE "id"=${id} RETURNING "id","name","slug","status"`; if(!rows[0]) throw new CoreError("NOT_FOUND","Category not found",404); return rows[0];}
export async function deleteCategory(id:string){try{const rows=await db.$queryRaw`DELETE FROM "category" WHERE "id"=${id} RETURNING "id"`;if(!rows[0])throw new CoreError("NOT_FOUND","Category not found",404);return null}catch(e){if(e instanceof CoreError)throw e;throw new CoreError("CONFLICT","Category is referenced by events",409)}}
export async function listEvents(q:any){const p=page(q.page), l=limit(q.limit);const off=(p-1)*l;const rows=await db.$queryRawUnsafe(`SELECT e.*, c.name AS category_name, c.slug AS category_slug FROM "event" e JOIN "category" c ON c.id=e.category_id WHERE e.status='PUBLISHED' ${q.search?`AND (e.title ILIKE $1 OR e.description ILIKE $1)`:''} ${q.city?`AND e.city ILIKE $2`:''} ORDER BY ${q.sort==='date'?'e.starts_at':'e.created_at'} ${q.order==='asc'?'ASC':'DESC'} LIMIT $${q.search&&q.city?3:q.search||q.city?2:1} OFFSET $${q.search&&q.city?4:q.search||q.city?3:2}`,...(q.search&&q.city?[`%${q.search}%`,`%${q.city}%`,l,off]:q.search?[`%${q.search}%`,l,off]:q.city?[`%${q.city}%`,l,off]:[l,off]));return {rows,meta:{page:p,limit:l,total:rows.length,totalPages:rows.length?Math.ceil(rows.length/l):0,hasNext:rows.length===l,hasPrev:p>1}};}
export async function eventBySlug(slug:string){const rows=await db.$queryRaw`SELECT e.*, c.name AS category_name, c.slug AS category_slug FROM "event" e JOIN "category" c ON c.id=e.category_id WHERE e.slug=${slug} AND e.status='PUBLISHED'`;if(!rows[0])throw new CoreError("NOT_FOUND","Event not found",404);return rows[0];}
export async function organizerFor(userId:string){const rows=await db.$queryRaw`SELECT * FROM "organizer_profile" WHERE "user_id"=${userId} LIMIT 1`;if(!rows[0])throw new CoreError("FORBIDDEN","Organizer profile required",403);return rows[0];}
export async function createEvent(userId:string,data:any){const org=await organizerFor(userId);const id=crypto.randomUUID();await db.$executeRaw`INSERT INTO "event" ("id","organizer_id","category_id","venue_id","title","slug","description","city","starts_at","ends_at","capacity","status","featured","created_at","updated_at") VALUES (${id},${org.id},${data.categoryId},${data.venueId??null},${data.title},${data.slug},${data.description??null},${data.city??null},${data.startsAt},${data.endsAt},${data.capacity??null},'DRAFT',false,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`;return {id,...data,status:"DRAFT",organizerId:org.id};}
export async function eventOwned(userId:string,id:string){const rows=await db.$queryRaw`SELECT e.*,o.user_id FROM "event" e JOIN "organizer_profile" o ON o.id=e.organizer_id WHERE e.id=${id}`;if(!rows[0])throw new CoreError("NOT_FOUND","Event not found",404);if(rows[0].user_id!==userId)throw new CoreError("FORBIDDEN","You do not own this event",403);return rows[0];}
export async function publishEvent(userId:string,id:string,admin=false){const e=admin?((await db.$queryRaw`SELECT * FROM "event" WHERE "id"=${id}`)[0]):await eventOwned(userId,id);if(!e)throw new CoreError("NOT_FOUND","Event not found",404);if(e.status!=="DRAFT")throw new CoreError("INVALID_STATE","Only draft events can be published",409);const count=await db.$queryRaw`SELECT count(*)::int AS n FROM "ticket_type" WHERE "event_id"=${id}`;if(!count[0]||count[0].n<1)throw new CoreError("VALIDATION_ERROR","At least one ticket type is required",400);return (await db.$queryRaw`UPDATE "event" SET "status"='PUBLISHED',"updated_at"=CURRENT_TIMESTAMP WHERE "id"=${id} RETURNING *`)[0];}
export async function cancelEvent(userId:string,id:string,admin=false){if(!admin)await eventOwned(userId,id);const rows=await db.$queryRaw`UPDATE "event" SET "status"='CANCELLED',"updated_at"=CURRENT_TIMESTAMP WHERE "id"=${id} AND "status" IN ('DRAFT','PUBLISHED') RETURNING *`;if(!rows[0])throw new CoreError("INVALID_STATE","Event cannot be cancelled",409);return rows[0];}
