import crypto from "node:crypto";
import type { Request, Response } from "express";
import type { AuthenticatedRequest } from "../../middleware/auth.js";
import { registerSchema, loginSchema, forgotPasswordSchema, resetPasswordSchema, verifyEmailSchema, changePasswordSchema, organizerUpgradeSchema } from "@festify/validation";
import { AuthError, registerUser, loginUser, revokeSession, rotateRefresh, verifyEmail, forgotPassword, resetPassword, changePassword } from "./auth.services.js";
import { ACCESS_COOKIE, REFRESH_COOKIE, accessCookieOptions, refreshCookieOptions, clearAuthCookies } from "../../lib/auth.js";
import { prisma } from "../../lib/prisma.js";
const db = prisma as any;
function setCookies(res: Response, result: { access: string; refresh: string }) { res.cookie(ACCESS_COOKIE, result.access, accessCookieOptions); res.cookie(REFRESH_COOKIE, result.refresh, refreshCookieOptions); }
function errorResponse(res: Response, error: unknown) { const e = error instanceof AuthError ? error : new AuthError("INTERNAL_ERROR", "Internal server error", 500); return res.status(e.status).json({ success: false, error: { code: e.code, message: e.message } }); }
function context(req: Request) { return { ip: req.ip, headers: req.headers as Record<string, unknown> }; }
export async function register(req: Request, res: Response) { const parsed = registerSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid registration details", details: parsed.error.flatten().fieldErrors } }); try { const result = await registerUser(parsed.data, context(req)); setCookies(res, result); return res.status(201).json({ success: true, data: { user: result.user, ...(result.devToken ? { devToken: result.devToken } : {}) }, message: "Registration successful" }); } catch (e) { return errorResponse(res, e); } }
export async function login(req: Request, res: Response) { const parsed = loginSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid login details" } }); try { const result = await loginUser(parsed.data, context(req)); setCookies(res, result); return res.json({ success: true, data: { user: result.user }, message: "Login successful" }); } catch (e) { return errorResponse(res, e); } }
export async function logout(req: AuthenticatedRequest, res: Response) { try { if (req.user?.sessionId) await revokeSession(req.user.sessionId, req.user.id); clearAuthCookies(res); return res.json({ success: true, data: null, message: "Logout successful" }); } catch (e) { return errorResponse(res, e); } }
export async function refresh(req: Request, res: Response) { const raw = req.cookies?.[REFRESH_COOKIE]; if (!raw) return res.status(401).json({ success: false, error: { code: "UNAUTHENTICATED", message: "Authentication required" } }); try { const result = await rotateRefresh(raw, context(req)); setCookies(res, result); return res.json({ success: true, data: null, message: "Token refreshed" }); } catch (e) { clearAuthCookies(res); return errorResponse(res, e); } }
export async function me(req: AuthenticatedRequest, res: Response) { if (!req.user) return res.status(401).json({ success: false, error: { code: "UNAUTHENTICATED", message: "Authentication required" } }); const user = await prisma.user.findUnique({ where: { id: req.user.id } }); if (!user) return res.status(401).json({ success: false, error: { code: "UNAUTHENTICATED", message: "Authentication required" } }); return res.json({ success: true, data: { id: user.id, name: user.name, email: user.email, role: req.user.role, status: user.status } }); }
export async function forgot(req: Request, res: Response) { const parsed = forgotPasswordSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid email" } }); try { const result = await forgotPassword(parsed.data.email); return res.json({ success: true, data: result?.devToken ? { devToken: result.devToken } : null, message: "If the account exists, password reset instructions have been sent." }); } catch (e) { return errorResponse(res, e); } }
export async function reset(req: Request, res: Response) { const parsed = resetPasswordSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid reset details" } }); try { await resetPassword(parsed.data.token, parsed.data.password); clearAuthCookies(res); return res.json({ success: true, data: null, message: "Password reset successful" }); } catch (e) { return errorResponse(res, e); } }
export async function verify(req: Request, res: Response) { const parsed = verifyEmailSchema.safeParse(req.body); if (!parsed.success) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid verification token" } }); try { return res.json({ success: true, data: await verifyEmail(parsed.data.token), message: "Email verified" }); } catch (e) { return errorResponse(res, e); } }
export async function change(req: AuthenticatedRequest, res: Response) { const parsed = changePasswordSchema.safeParse(req.body); if (!parsed.success || !req.user) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid password details" } }); try { await changePassword(req.user.id, parsed.data.currentPassword, parsed.data.newPassword, req.user.sessionId!); return res.json({ success: true, data: null, message: "Password changed" }); } catch (e) { return errorResponse(res, e); } }
export async function organizerUpgrade(req: AuthenticatedRequest, res: Response) { const parsed = organizerUpgradeSchema.safeParse(req.body); if (!parsed.success || !req.user) return res.status(400).json({ success: false, error: { code: "VALIDATION_ERROR", message: "Invalid organizer details" } }); try { const existing = await db.$queryRaw<Array<any>>`SELECT id FROM "organizer_profile" WHERE "user_id"=${req.user.id} LIMIT 1`; if (existing[0]) return res.status(409).json({ success: false, error: { code: "CONFLICT", message: "Organizer profile already exists" } }); const id = crypto.randomUUID(); await db.$executeRaw`INSERT INTO "organizer_profile" ("id","user_id","organization_name","slug","bio","website","verification_status","created_at","updated_at") VALUES (${id},${req.user.id},${parsed.data.organizationName},${parsed.data.slug},${parsed.data.bio ?? null},${parsed.data.website ?? null},'PENDING',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`; return res.status(201).json({ success: true, data: { id, verificationStatus: "PENDING" }, message: "Organizer request submitted" }); } catch (e) { return errorResponse(res, e); } }
